security:
  basic:
    enabled: false

management:
  security:
    enabled: false

logging:
  level:
    io:
      pivotal: DEBUG
info:
  app: ${spring.application.name}
#spring: # <---NEW SECTION
#  cloud:
#    services:
#      registrationMethod: direct
